// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiqvfmspqdrdlaqedlfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcXZmbXNwcWRyZGxhcWVkbGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODAzNjIsImV4cCI6MjA2NjA1NjM2Mn0.XvzTs5Cn3c2sCFlrRK2aYhTOaxOq7Y_cJLc--4eQ5pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);